# Build stage
FROM node:20-alpine AS build

WORKDIR /app

# Copy package.json and lock file to leverage Docker cache
COPY package*.json ./

RUN npm install

# Copy source code and build
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine

# Copy built assets from build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
